//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Activity_Event = new HashSet<Activity_Event>();
        }
    
        public int Idevent { get; set; }
        public string event1 { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<int> cityID { get; set; }
        public Nullable<int> topicID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Event> Activity_Event { get; set; }
        public virtual City City { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
