//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Activity_User = new HashSet<Activity_User>();
        }
    
        public int Iduser { get; set; }
        public string FIO { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public Nullable<int> countryID { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> sexID { get; set; }
        public Nullable<int> topicID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_User> Activity_User { get; set; }
        public virtual Country Country { get; set; }
        public virtual Role Role { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
